// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "lightning/v2/envelope_v2.proto" (package "lightning.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message lightning.v2.EnvelopeDocument
 */
export interface EnvelopeDocument {
    /**
     * @generated from protobuf field: string format_version = 1
     */
    formatVersion: string; // "2.0"
    /**
     * @generated from protobuf field: lightning.v2.EnvelopeMeta meta = 2
     */
    meta?: EnvelopeMeta;
    /**
     * @generated from protobuf field: bytes compressed_payload = 3
     */
    compressedPayload: Uint8Array; // gzip → JSON(PlainSceneDocument)
}
/**
 * @generated from protobuf message lightning.v2.EnvelopeMeta
 */
export interface EnvelopeMeta {
    /**
     * @generated from protobuf field: string scene_id = 1
     */
    sceneId: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string author = 3
     */
    author: string;
    /**
     * @generated from protobuf field: int64 created_at_ms = 4
     */
    createdAtMs: bigint;
    /**
     * @generated from protobuf field: int64 compressed_size_bytes = 5
     */
    compressedSizeBytes: bigint;
    /**
     * @generated from protobuf field: int64 uncompressed_size_bytes = 6
     */
    uncompressedSizeBytes: bigint;
    /**
     * @generated from protobuf field: string sha256_hex = 7
     */
    sha256Hex: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class EnvelopeDocument$Type extends MessageType<EnvelopeDocument> {
    constructor() {
        super("lightning.v2.EnvelopeDocument", [
            { no: 1, name: "format_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "meta", kind: "message", T: () => EnvelopeMeta },
            { no: 3, name: "compressed_payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<EnvelopeDocument>): EnvelopeDocument {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.formatVersion = "";
        message.compressedPayload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<EnvelopeDocument>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnvelopeDocument): EnvelopeDocument {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string format_version */ 1:
                    message.formatVersion = reader.string();
                    break;
                case /* lightning.v2.EnvelopeMeta meta */ 2:
                    message.meta = EnvelopeMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* bytes compressed_payload */ 3:
                    message.compressedPayload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnvelopeDocument, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string format_version = 1; */
        if (message.formatVersion !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.formatVersion);
        /* lightning.v2.EnvelopeMeta meta = 2; */
        if (message.meta)
            EnvelopeMeta.internalBinaryWrite(message.meta, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bytes compressed_payload = 3; */
        if (message.compressedPayload.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.compressedPayload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.EnvelopeDocument
 */
export const EnvelopeDocument = new EnvelopeDocument$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnvelopeMeta$Type extends MessageType<EnvelopeMeta> {
    constructor() {
        super("lightning.v2.EnvelopeMeta", [
            { no: 1, name: "scene_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "author", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "compressed_size_bytes", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "uncompressed_size_bytes", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "sha256_hex", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EnvelopeMeta>): EnvelopeMeta {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sceneId = "";
        message.name = "";
        message.author = "";
        message.createdAtMs = 0n;
        message.compressedSizeBytes = 0n;
        message.uncompressedSizeBytes = 0n;
        message.sha256Hex = "";
        if (value !== undefined)
            reflectionMergePartial<EnvelopeMeta>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnvelopeMeta): EnvelopeMeta {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string scene_id */ 1:
                    message.sceneId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string author */ 3:
                    message.author = reader.string();
                    break;
                case /* int64 created_at_ms */ 4:
                    message.createdAtMs = reader.int64().toBigInt();
                    break;
                case /* int64 compressed_size_bytes */ 5:
                    message.compressedSizeBytes = reader.int64().toBigInt();
                    break;
                case /* int64 uncompressed_size_bytes */ 6:
                    message.uncompressedSizeBytes = reader.int64().toBigInt();
                    break;
                case /* string sha256_hex */ 7:
                    message.sha256Hex = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnvelopeMeta, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string scene_id = 1; */
        if (message.sceneId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sceneId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string author = 3; */
        if (message.author !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.author);
        /* int64 created_at_ms = 4; */
        if (message.createdAtMs !== 0n)
            writer.tag(4, WireType.Varint).int64(message.createdAtMs);
        /* int64 compressed_size_bytes = 5; */
        if (message.compressedSizeBytes !== 0n)
            writer.tag(5, WireType.Varint).int64(message.compressedSizeBytes);
        /* int64 uncompressed_size_bytes = 6; */
        if (message.uncompressedSizeBytes !== 0n)
            writer.tag(6, WireType.Varint).int64(message.uncompressedSizeBytes);
        /* string sha256_hex = 7; */
        if (message.sha256Hex !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.sha256Hex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.EnvelopeMeta
 */
export const EnvelopeMeta = new EnvelopeMeta$Type();
