// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "lightning/v2/plain_v2.proto" (package "lightning.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Plain v2 — 完整场景数据，含 v2 新增字段
 *
 * @generated from protobuf message lightning.v2.PlainSceneDocument
 */
export interface PlainSceneDocument {
    /**
     * @generated from protobuf field: string format_version = 1
     */
    formatVersion: string; // "2.0"
    /**
     * @generated from protobuf field: lightning.v2.SceneMeta meta = 2
     */
    meta?: SceneMeta;
    /**
     * @generated from protobuf field: repeated lightning.v2.WorldFrame frames = 3
     */
    frames: WorldFrame[];
    /**
     * @generated from protobuf field: map<string, lightning.v2.BlockState> block_palette = 4
     */
    blockPalette: {
        [key: string]: BlockState;
    };
    /**
     * @generated from protobuf field: lightning.v2.MaterialLibrary materials = 5
     */
    materials?: MaterialLibrary;
    /**
     * v2 新增
     *
     * @generated from protobuf field: repeated lightning.v2.AnnotationBox annotations = 6
     */
    annotations: AnnotationBox[];
    /**
     * @generated from protobuf field: repeated lightning.v2.Label labels = 7
     */
    labels: Label[];
    /**
     * @generated from protobuf field: lightning.v2.StatsTemplate stats_template = 8
     */
    statsTemplate?: StatsTemplate;
}
/**
 * @generated from protobuf message lightning.v2.SceneMeta
 */
export interface SceneMeta {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string author = 2
     */
    author: string;
    /**
     * @generated from protobuf field: int64 created_at_ms = 3
     */
    createdAtMs: bigint;
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
    /**
     * @generated from protobuf field: repeated string tags = 5
     */
    tags: string[];
    /**
     * @generated from protobuf field: lightning.v2.BlockPos origin = 6
     */
    origin?: BlockPos;
}
/**
 * @generated from protobuf message lightning.v2.BlockPos
 */
export interface BlockPos {
    /**
     * @generated from protobuf field: int32 x = 1
     */
    x: number;
    /**
     * @generated from protobuf field: int32 y = 2
     */
    y: number;
    /**
     * @generated from protobuf field: int32 z = 3
     */
    z: number;
}
/**
 * @generated from protobuf message lightning.v2.WorldFrame
 */
export interface WorldFrame {
    /**
     * @generated from protobuf field: string label = 1
     */
    label: string;
    /**
     * @generated from protobuf field: int32 index = 2
     */
    index: number;
    /**
     * @generated from protobuf field: repeated lightning.v2.BlockInstance blocks = 3
     */
    blocks: BlockInstance[];
    /**
     * @generated from protobuf field: repeated lightning.v2.EntityInstance entities = 4
     */
    entities: EntityInstance[];
}
/**
 * @generated from protobuf message lightning.v2.BlockInstance
 */
export interface BlockInstance {
    /**
     * @generated from protobuf field: lightning.v2.BlockPos pos = 1
     */
    pos?: BlockPos;
    /**
     * @generated from protobuf field: string block_state_id = 2
     */
    blockStateId: string;
    /**
     * @generated from protobuf field: map<string, string> nbt = 3
     */
    nbt: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: repeated lightning.v2.BlockPart parts = 4
     */
    parts: BlockPart[]; // v2 新增
    /**
     * @generated from protobuf field: lightning.v2.GuiState gui_state = 5
     */
    guiState?: GuiState; // v2 新增
}
/**
 * @generated from protobuf message lightning.v2.BlockPart
 */
export interface BlockPart {
    /**
     * @generated from protobuf field: string local_id = 1
     */
    localId: string; // 父块内唯一标识
    /**
     * @generated from protobuf field: string part_kind = 2
     */
    partKind: string; // modid:类型
    /**
     * @generated from protobuf field: int32 direction = 3
     */
    direction: number; // -1=无, 0-5=DUNSWE, 6=CENTER
    /**
     * @generated from protobuf field: map<string, string> properties = 4
     */
    properties: {
        [key: string]: string;
    }; // 部件属性
    /**
     * @generated from protobuf field: string tooltip = 5
     */
    tooltip: string; // 独立 tooltip
}
/**
 * @generated from protobuf message lightning.v2.GuiState
 */
export interface GuiState {
    /**
     * @generated from protobuf field: string layout_id = 1
     */
    layoutId: string;
    /**
     * @generated from protobuf field: repeated lightning.v2.ItemSlot item_slots = 2
     */
    itemSlots: ItemSlot[];
    /**
     * @generated from protobuf field: repeated lightning.v2.FluidTank fluid_tanks = 3
     */
    fluidTanks: FluidTank[];
    /**
     * @generated from protobuf field: lightning.v2.EnergyState energy = 4
     */
    energy?: EnergyState;
    /**
     * @generated from protobuf field: map<string, string> config = 5
     */
    config: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message lightning.v2.ItemSlot
 */
export interface ItemSlot {
    /**
     * @generated from protobuf field: int32 slot_index = 1
     */
    slotIndex: number;
    /**
     * @generated from protobuf field: string item_id = 2
     */
    itemId: string;
    /**
     * @generated from protobuf field: int32 count = 3
     */
    count: number;
    /**
     * @generated from protobuf field: int32 damage = 4
     */
    damage: number;
    /**
     * @generated from protobuf field: map<string, string> nbt = 5
     */
    nbt: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message lightning.v2.FluidTank
 */
export interface FluidTank {
    /**
     * @generated from protobuf field: int32 tank_index = 1
     */
    tankIndex: number;
    /**
     * @generated from protobuf field: string fluid_id = 2
     */
    fluidId: string;
    /**
     * @generated from protobuf field: int64 amount_mb = 3
     */
    amountMb: bigint;
    /**
     * @generated from protobuf field: int64 capacity_mb = 4
     */
    capacityMb: bigint;
}
/**
 * @generated from protobuf message lightning.v2.EnergyState
 */
export interface EnergyState {
    /**
     * @generated from protobuf field: int64 stored_eu = 1
     */
    storedEu: bigint;
    /**
     * @generated from protobuf field: int64 capacity_eu = 2
     */
    capacityEu: bigint;
}
/**
 * @generated from protobuf message lightning.v2.BlockState
 */
export interface BlockState {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: map<string, string> properties = 2
     */
    properties: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message lightning.v2.EntityInstance
 */
export interface EntityInstance {
    /**
     * @generated from protobuf field: lightning.v2.BlockPos pos = 1
     */
    pos?: BlockPos;
    /**
     * @generated from protobuf field: string entity_id = 2
     */
    entityId: string;
    /**
     * @generated from protobuf field: map<string, string> nbt = 3
     */
    nbt: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message lightning.v2.MaterialLibrary
 */
export interface MaterialLibrary {
    /**
     * @generated from protobuf field: repeated lightning.v2.MaterialEntry entries = 1
     */
    entries: MaterialEntry[];
}
/**
 * @generated from protobuf message lightning.v2.MaterialEntry
 */
export interface MaterialEntry {
    /**
     * @generated from protobuf field: string key = 1
     */
    key: string;
    /**
     * @generated from protobuf field: bytes texture_png = 2
     */
    texturePng: Uint8Array;
    /**
     * @generated from protobuf field: string blend_mode = 3
     */
    blendMode: string;
    /**
     * @generated from protobuf field: bool is_animated = 4
     */
    isAnimated: boolean;
    /**
     * @generated from protobuf field: int32 animation_ticks_per_frame = 5
     */
    animationTicksPerFrame: number;
    /**
     * @generated from protobuf field: int32 animation_frame_count = 6
     */
    animationFrameCount: number;
}
/**
 * @generated from protobuf message lightning.v2.AnnotationBox
 */
export interface AnnotationBox {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string; // Markdown
    /**
     * @generated from protobuf field: lightning.v2.BlockPos min = 4
     */
    min?: BlockPos;
    /**
     * @generated from protobuf field: lightning.v2.BlockPos max = 5
     */
    max?: BlockPos;
    /**
     * @generated from protobuf field: string color = 6
     */
    color: string;
    /**
     * @generated from protobuf field: bool visible = 7
     */
    visible: boolean;
    /**
     * @generated from protobuf field: repeated lightning.v2.PartRef part_refs = 8
     */
    partRefs: PartRef[]; // 可选：定向注解 part
    /**
     * @generated from protobuf field: int64 created_at = 9
     */
    createdAt: bigint;
    /**
     * @generated from protobuf field: int64 updated_at = 10
     */
    updatedAt: bigint;
}
/**
 * @generated from protobuf message lightning.v2.PartRef
 */
export interface PartRef {
    /**
     * @generated from protobuf field: lightning.v2.BlockPos block_pos = 1
     */
    blockPos?: BlockPos;
    /**
     * @generated from protobuf field: string part_local_id = 2
     */
    partLocalId: string;
}
/**
 * @generated from protobuf message lightning.v2.Label
 */
export interface Label {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string text = 2
     */
    text: string;
    /**
     * @generated from protobuf field: float x = 3
     */
    x: number;
    /**
     * @generated from protobuf field: float y = 4
     */
    y: number;
    /**
     * @generated from protobuf field: float z = 5
     */
    z: number;
    /**
     * @generated from protobuf field: string color = 6
     */
    color: string;
    /**
     * @generated from protobuf field: int32 font_size = 7
     */
    fontSize: number;
    /**
     * @generated from protobuf field: bool visible = 8
     */
    visible: boolean;
}
/**
 * @generated from protobuf message lightning.v2.StatsTemplate
 */
export interface StatsTemplate {
    /**
     * @generated from protobuf field: string mode = 1
     */
    mode: string; // "auto" | "custom"
    /**
     * @generated from protobuf field: repeated lightning.v2.StatsGroup groups = 2
     */
    groups: StatsGroup[];
    /**
     * @generated from protobuf field: bool show_others = 3
     */
    showOthers: boolean;
}
/**
 * @generated from protobuf message lightning.v2.StatsGroup
 */
export interface StatsGroup {
    /**
     * @generated from protobuf field: string label = 1
     */
    label: string;
    /**
     * @generated from protobuf field: repeated lightning.v2.StatsEntry entries = 2
     */
    entries: StatsEntry[];
}
/**
 * @generated from protobuf message lightning.v2.StatsEntry
 */
export interface StatsEntry {
    /**
     * @generated from protobuf field: string block_state_id = 1
     */
    blockStateId: string;
    /**
     * @generated from protobuf field: string label_override = 2
     */
    labelOverride: string;
    /**
     * @generated from protobuf field: string icon_source = 3
     */
    iconSource: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class PlainSceneDocument$Type extends MessageType<PlainSceneDocument> {
    constructor() {
        super("lightning.v2.PlainSceneDocument", [
            { no: 1, name: "format_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "meta", kind: "message", T: () => SceneMeta },
            { no: 3, name: "frames", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WorldFrame },
            { no: 4, name: "block_palette", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => BlockState } },
            { no: 5, name: "materials", kind: "message", T: () => MaterialLibrary },
            { no: 6, name: "annotations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AnnotationBox },
            { no: 7, name: "labels", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Label },
            { no: 8, name: "stats_template", kind: "message", T: () => StatsTemplate }
        ]);
    }
    create(value?: PartialMessage<PlainSceneDocument>): PlainSceneDocument {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.formatVersion = "";
        message.frames = [];
        message.blockPalette = {};
        message.annotations = [];
        message.labels = [];
        if (value !== undefined)
            reflectionMergePartial<PlainSceneDocument>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlainSceneDocument): PlainSceneDocument {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string format_version */ 1:
                    message.formatVersion = reader.string();
                    break;
                case /* lightning.v2.SceneMeta meta */ 2:
                    message.meta = SceneMeta.internalBinaryRead(reader, reader.uint32(), options, message.meta);
                    break;
                case /* repeated lightning.v2.WorldFrame frames */ 3:
                    message.frames.push(WorldFrame.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* map<string, lightning.v2.BlockState> block_palette */ 4:
                    this.binaryReadMap4(message.blockPalette, reader, options);
                    break;
                case /* lightning.v2.MaterialLibrary materials */ 5:
                    message.materials = MaterialLibrary.internalBinaryRead(reader, reader.uint32(), options, message.materials);
                    break;
                case /* repeated lightning.v2.AnnotationBox annotations */ 6:
                    message.annotations.push(AnnotationBox.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated lightning.v2.Label labels */ 7:
                    message.labels.push(Label.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* lightning.v2.StatsTemplate stats_template */ 8:
                    message.statsTemplate = StatsTemplate.internalBinaryRead(reader, reader.uint32(), options, message.statsTemplate);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap4(map: PlainSceneDocument["blockPalette"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof PlainSceneDocument["blockPalette"] | undefined, val: PlainSceneDocument["blockPalette"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = BlockState.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.PlainSceneDocument.block_palette");
            }
        }
        map[key ?? ""] = val ?? BlockState.create();
    }
    internalBinaryWrite(message: PlainSceneDocument, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string format_version = 1; */
        if (message.formatVersion !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.formatVersion);
        /* lightning.v2.SceneMeta meta = 2; */
        if (message.meta)
            SceneMeta.internalBinaryWrite(message.meta, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated lightning.v2.WorldFrame frames = 3; */
        for (let i = 0; i < message.frames.length; i++)
            WorldFrame.internalBinaryWrite(message.frames[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* map<string, lightning.v2.BlockState> block_palette = 4; */
        for (let k of globalThis.Object.keys(message.blockPalette)) {
            writer.tag(4, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            BlockState.internalBinaryWrite(message.blockPalette[k], writer, options);
            writer.join().join();
        }
        /* lightning.v2.MaterialLibrary materials = 5; */
        if (message.materials)
            MaterialLibrary.internalBinaryWrite(message.materials, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* repeated lightning.v2.AnnotationBox annotations = 6; */
        for (let i = 0; i < message.annotations.length; i++)
            AnnotationBox.internalBinaryWrite(message.annotations[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* repeated lightning.v2.Label labels = 7; */
        for (let i = 0; i < message.labels.length; i++)
            Label.internalBinaryWrite(message.labels[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* lightning.v2.StatsTemplate stats_template = 8; */
        if (message.statsTemplate)
            StatsTemplate.internalBinaryWrite(message.statsTemplate, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.PlainSceneDocument
 */
export const PlainSceneDocument = new PlainSceneDocument$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SceneMeta$Type extends MessageType<SceneMeta> {
    constructor() {
        super("lightning.v2.SceneMeta", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "author", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "created_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "tags", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "origin", kind: "message", T: () => BlockPos }
        ]);
    }
    create(value?: PartialMessage<SceneMeta>): SceneMeta {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.author = "";
        message.createdAtMs = 0n;
        message.description = "";
        message.tags = [];
        if (value !== undefined)
            reflectionMergePartial<SceneMeta>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneMeta): SceneMeta {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string author */ 2:
                    message.author = reader.string();
                    break;
                case /* int64 created_at_ms */ 3:
                    message.createdAtMs = reader.int64().toBigInt();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* repeated string tags */ 5:
                    message.tags.push(reader.string());
                    break;
                case /* lightning.v2.BlockPos origin */ 6:
                    message.origin = BlockPos.internalBinaryRead(reader, reader.uint32(), options, message.origin);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SceneMeta, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string author = 2; */
        if (message.author !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.author);
        /* int64 created_at_ms = 3; */
        if (message.createdAtMs !== 0n)
            writer.tag(3, WireType.Varint).int64(message.createdAtMs);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* repeated string tags = 5; */
        for (let i = 0; i < message.tags.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.tags[i]);
        /* lightning.v2.BlockPos origin = 6; */
        if (message.origin)
            BlockPos.internalBinaryWrite(message.origin, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.SceneMeta
 */
export const SceneMeta = new SceneMeta$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockPos$Type extends MessageType<BlockPos> {
    constructor() {
        super("lightning.v2.BlockPos", [
            { no: 1, name: "x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "z", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<BlockPos>): BlockPos {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.x = 0;
        message.y = 0;
        message.z = 0;
        if (value !== undefined)
            reflectionMergePartial<BlockPos>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockPos): BlockPos {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 x */ 1:
                    message.x = reader.int32();
                    break;
                case /* int32 y */ 2:
                    message.y = reader.int32();
                    break;
                case /* int32 z */ 3:
                    message.z = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlockPos, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 x = 1; */
        if (message.x !== 0)
            writer.tag(1, WireType.Varint).int32(message.x);
        /* int32 y = 2; */
        if (message.y !== 0)
            writer.tag(2, WireType.Varint).int32(message.y);
        /* int32 z = 3; */
        if (message.z !== 0)
            writer.tag(3, WireType.Varint).int32(message.z);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.BlockPos
 */
export const BlockPos = new BlockPos$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WorldFrame$Type extends MessageType<WorldFrame> {
    constructor() {
        super("lightning.v2.WorldFrame", [
            { no: 1, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "blocks", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => BlockInstance },
            { no: 4, name: "entities", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EntityInstance }
        ]);
    }
    create(value?: PartialMessage<WorldFrame>): WorldFrame {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.label = "";
        message.index = 0;
        message.blocks = [];
        message.entities = [];
        if (value !== undefined)
            reflectionMergePartial<WorldFrame>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorldFrame): WorldFrame {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string label */ 1:
                    message.label = reader.string();
                    break;
                case /* int32 index */ 2:
                    message.index = reader.int32();
                    break;
                case /* repeated lightning.v2.BlockInstance blocks */ 3:
                    message.blocks.push(BlockInstance.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated lightning.v2.EntityInstance entities */ 4:
                    message.entities.push(EntityInstance.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorldFrame, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string label = 1; */
        if (message.label !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.label);
        /* int32 index = 2; */
        if (message.index !== 0)
            writer.tag(2, WireType.Varint).int32(message.index);
        /* repeated lightning.v2.BlockInstance blocks = 3; */
        for (let i = 0; i < message.blocks.length; i++)
            BlockInstance.internalBinaryWrite(message.blocks[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated lightning.v2.EntityInstance entities = 4; */
        for (let i = 0; i < message.entities.length; i++)
            EntityInstance.internalBinaryWrite(message.entities[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.WorldFrame
 */
export const WorldFrame = new WorldFrame$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockInstance$Type extends MessageType<BlockInstance> {
    constructor() {
        super("lightning.v2.BlockInstance", [
            { no: 1, name: "pos", kind: "message", T: () => BlockPos },
            { no: 2, name: "block_state_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "nbt", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 4, name: "parts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => BlockPart },
            { no: 5, name: "gui_state", kind: "message", T: () => GuiState }
        ]);
    }
    create(value?: PartialMessage<BlockInstance>): BlockInstance {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.blockStateId = "";
        message.nbt = {};
        message.parts = [];
        if (value !== undefined)
            reflectionMergePartial<BlockInstance>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockInstance): BlockInstance {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* lightning.v2.BlockPos pos */ 1:
                    message.pos = BlockPos.internalBinaryRead(reader, reader.uint32(), options, message.pos);
                    break;
                case /* string block_state_id */ 2:
                    message.blockStateId = reader.string();
                    break;
                case /* map<string, string> nbt */ 3:
                    this.binaryReadMap3(message.nbt, reader, options);
                    break;
                case /* repeated lightning.v2.BlockPart parts */ 4:
                    message.parts.push(BlockPart.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* lightning.v2.GuiState gui_state */ 5:
                    message.guiState = GuiState.internalBinaryRead(reader, reader.uint32(), options, message.guiState);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap3(map: BlockInstance["nbt"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BlockInstance["nbt"] | undefined, val: BlockInstance["nbt"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.BlockInstance.nbt");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: BlockInstance, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* lightning.v2.BlockPos pos = 1; */
        if (message.pos)
            BlockPos.internalBinaryWrite(message.pos, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string block_state_id = 2; */
        if (message.blockStateId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.blockStateId);
        /* map<string, string> nbt = 3; */
        for (let k of globalThis.Object.keys(message.nbt))
            writer.tag(3, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.nbt[k]).join();
        /* repeated lightning.v2.BlockPart parts = 4; */
        for (let i = 0; i < message.parts.length; i++)
            BlockPart.internalBinaryWrite(message.parts[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* lightning.v2.GuiState gui_state = 5; */
        if (message.guiState)
            GuiState.internalBinaryWrite(message.guiState, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.BlockInstance
 */
export const BlockInstance = new BlockInstance$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockPart$Type extends MessageType<BlockPart> {
    constructor() {
        super("lightning.v2.BlockPart", [
            { no: 1, name: "local_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "part_kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "direction", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "properties", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 5, name: "tooltip", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BlockPart>): BlockPart {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.localId = "";
        message.partKind = "";
        message.direction = 0;
        message.properties = {};
        message.tooltip = "";
        if (value !== undefined)
            reflectionMergePartial<BlockPart>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockPart): BlockPart {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string local_id */ 1:
                    message.localId = reader.string();
                    break;
                case /* string part_kind */ 2:
                    message.partKind = reader.string();
                    break;
                case /* int32 direction */ 3:
                    message.direction = reader.int32();
                    break;
                case /* map<string, string> properties */ 4:
                    this.binaryReadMap4(message.properties, reader, options);
                    break;
                case /* string tooltip */ 5:
                    message.tooltip = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap4(map: BlockPart["properties"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BlockPart["properties"] | undefined, val: BlockPart["properties"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.BlockPart.properties");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: BlockPart, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string local_id = 1; */
        if (message.localId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.localId);
        /* string part_kind = 2; */
        if (message.partKind !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.partKind);
        /* int32 direction = 3; */
        if (message.direction !== 0)
            writer.tag(3, WireType.Varint).int32(message.direction);
        /* map<string, string> properties = 4; */
        for (let k of globalThis.Object.keys(message.properties))
            writer.tag(4, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.properties[k]).join();
        /* string tooltip = 5; */
        if (message.tooltip !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.tooltip);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.BlockPart
 */
export const BlockPart = new BlockPart$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GuiState$Type extends MessageType<GuiState> {
    constructor() {
        super("lightning.v2.GuiState", [
            { no: 1, name: "layout_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "item_slots", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ItemSlot },
            { no: 3, name: "fluid_tanks", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FluidTank },
            { no: 4, name: "energy", kind: "message", T: () => EnergyState },
            { no: 5, name: "config", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<GuiState>): GuiState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.layoutId = "";
        message.itemSlots = [];
        message.fluidTanks = [];
        message.config = {};
        if (value !== undefined)
            reflectionMergePartial<GuiState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GuiState): GuiState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string layout_id */ 1:
                    message.layoutId = reader.string();
                    break;
                case /* repeated lightning.v2.ItemSlot item_slots */ 2:
                    message.itemSlots.push(ItemSlot.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated lightning.v2.FluidTank fluid_tanks */ 3:
                    message.fluidTanks.push(FluidTank.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* lightning.v2.EnergyState energy */ 4:
                    message.energy = EnergyState.internalBinaryRead(reader, reader.uint32(), options, message.energy);
                    break;
                case /* map<string, string> config */ 5:
                    this.binaryReadMap5(message.config, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap5(map: GuiState["config"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof GuiState["config"] | undefined, val: GuiState["config"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.GuiState.config");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: GuiState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string layout_id = 1; */
        if (message.layoutId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.layoutId);
        /* repeated lightning.v2.ItemSlot item_slots = 2; */
        for (let i = 0; i < message.itemSlots.length; i++)
            ItemSlot.internalBinaryWrite(message.itemSlots[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated lightning.v2.FluidTank fluid_tanks = 3; */
        for (let i = 0; i < message.fluidTanks.length; i++)
            FluidTank.internalBinaryWrite(message.fluidTanks[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* lightning.v2.EnergyState energy = 4; */
        if (message.energy)
            EnergyState.internalBinaryWrite(message.energy, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* map<string, string> config = 5; */
        for (let k of globalThis.Object.keys(message.config))
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.config[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.GuiState
 */
export const GuiState = new GuiState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ItemSlot$Type extends MessageType<ItemSlot> {
    constructor() {
        super("lightning.v2.ItemSlot", [
            { no: 1, name: "slot_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "item_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "damage", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "nbt", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<ItemSlot>): ItemSlot {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slotIndex = 0;
        message.itemId = "";
        message.count = 0;
        message.damage = 0;
        message.nbt = {};
        if (value !== undefined)
            reflectionMergePartial<ItemSlot>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ItemSlot): ItemSlot {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 slot_index */ 1:
                    message.slotIndex = reader.int32();
                    break;
                case /* string item_id */ 2:
                    message.itemId = reader.string();
                    break;
                case /* int32 count */ 3:
                    message.count = reader.int32();
                    break;
                case /* int32 damage */ 4:
                    message.damage = reader.int32();
                    break;
                case /* map<string, string> nbt */ 5:
                    this.binaryReadMap5(message.nbt, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap5(map: ItemSlot["nbt"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof ItemSlot["nbt"] | undefined, val: ItemSlot["nbt"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.ItemSlot.nbt");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: ItemSlot, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 slot_index = 1; */
        if (message.slotIndex !== 0)
            writer.tag(1, WireType.Varint).int32(message.slotIndex);
        /* string item_id = 2; */
        if (message.itemId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.itemId);
        /* int32 count = 3; */
        if (message.count !== 0)
            writer.tag(3, WireType.Varint).int32(message.count);
        /* int32 damage = 4; */
        if (message.damage !== 0)
            writer.tag(4, WireType.Varint).int32(message.damage);
        /* map<string, string> nbt = 5; */
        for (let k of globalThis.Object.keys(message.nbt))
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.nbt[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.ItemSlot
 */
export const ItemSlot = new ItemSlot$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FluidTank$Type extends MessageType<FluidTank> {
    constructor() {
        super("lightning.v2.FluidTank", [
            { no: 1, name: "tank_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "fluid_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount_mb", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "capacity_mb", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<FluidTank>): FluidTank {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tankIndex = 0;
        message.fluidId = "";
        message.amountMb = 0n;
        message.capacityMb = 0n;
        if (value !== undefined)
            reflectionMergePartial<FluidTank>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FluidTank): FluidTank {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 tank_index */ 1:
                    message.tankIndex = reader.int32();
                    break;
                case /* string fluid_id */ 2:
                    message.fluidId = reader.string();
                    break;
                case /* int64 amount_mb */ 3:
                    message.amountMb = reader.int64().toBigInt();
                    break;
                case /* int64 capacity_mb */ 4:
                    message.capacityMb = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FluidTank, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 tank_index = 1; */
        if (message.tankIndex !== 0)
            writer.tag(1, WireType.Varint).int32(message.tankIndex);
        /* string fluid_id = 2; */
        if (message.fluidId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fluidId);
        /* int64 amount_mb = 3; */
        if (message.amountMb !== 0n)
            writer.tag(3, WireType.Varint).int64(message.amountMb);
        /* int64 capacity_mb = 4; */
        if (message.capacityMb !== 0n)
            writer.tag(4, WireType.Varint).int64(message.capacityMb);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.FluidTank
 */
export const FluidTank = new FluidTank$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnergyState$Type extends MessageType<EnergyState> {
    constructor() {
        super("lightning.v2.EnergyState", [
            { no: 1, name: "stored_eu", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "capacity_eu", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<EnergyState>): EnergyState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.storedEu = 0n;
        message.capacityEu = 0n;
        if (value !== undefined)
            reflectionMergePartial<EnergyState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnergyState): EnergyState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 stored_eu */ 1:
                    message.storedEu = reader.int64().toBigInt();
                    break;
                case /* int64 capacity_eu */ 2:
                    message.capacityEu = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnergyState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 stored_eu = 1; */
        if (message.storedEu !== 0n)
            writer.tag(1, WireType.Varint).int64(message.storedEu);
        /* int64 capacity_eu = 2; */
        if (message.capacityEu !== 0n)
            writer.tag(2, WireType.Varint).int64(message.capacityEu);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.EnergyState
 */
export const EnergyState = new EnergyState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockState$Type extends MessageType<BlockState> {
    constructor() {
        super("lightning.v2.BlockState", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "properties", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<BlockState>): BlockState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.properties = {};
        if (value !== undefined)
            reflectionMergePartial<BlockState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockState): BlockState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* map<string, string> properties */ 2:
                    this.binaryReadMap2(message.properties, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: BlockState["properties"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BlockState["properties"] | undefined, val: BlockState["properties"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.BlockState.properties");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: BlockState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* map<string, string> properties = 2; */
        for (let k of globalThis.Object.keys(message.properties))
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.properties[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.BlockState
 */
export const BlockState = new BlockState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EntityInstance$Type extends MessageType<EntityInstance> {
    constructor() {
        super("lightning.v2.EntityInstance", [
            { no: 1, name: "pos", kind: "message", T: () => BlockPos },
            { no: 2, name: "entity_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "nbt", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<EntityInstance>): EntityInstance {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.entityId = "";
        message.nbt = {};
        if (value !== undefined)
            reflectionMergePartial<EntityInstance>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EntityInstance): EntityInstance {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* lightning.v2.BlockPos pos */ 1:
                    message.pos = BlockPos.internalBinaryRead(reader, reader.uint32(), options, message.pos);
                    break;
                case /* string entity_id */ 2:
                    message.entityId = reader.string();
                    break;
                case /* map<string, string> nbt */ 3:
                    this.binaryReadMap3(message.nbt, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap3(map: EntityInstance["nbt"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof EntityInstance["nbt"] | undefined, val: EntityInstance["nbt"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for lightning.v2.EntityInstance.nbt");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: EntityInstance, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* lightning.v2.BlockPos pos = 1; */
        if (message.pos)
            BlockPos.internalBinaryWrite(message.pos, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string entity_id = 2; */
        if (message.entityId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.entityId);
        /* map<string, string> nbt = 3; */
        for (let k of globalThis.Object.keys(message.nbt))
            writer.tag(3, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.nbt[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.EntityInstance
 */
export const EntityInstance = new EntityInstance$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MaterialLibrary$Type extends MessageType<MaterialLibrary> {
    constructor() {
        super("lightning.v2.MaterialLibrary", [
            { no: 1, name: "entries", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MaterialEntry }
        ]);
    }
    create(value?: PartialMessage<MaterialLibrary>): MaterialLibrary {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.entries = [];
        if (value !== undefined)
            reflectionMergePartial<MaterialLibrary>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MaterialLibrary): MaterialLibrary {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated lightning.v2.MaterialEntry entries */ 1:
                    message.entries.push(MaterialEntry.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MaterialLibrary, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated lightning.v2.MaterialEntry entries = 1; */
        for (let i = 0; i < message.entries.length; i++)
            MaterialEntry.internalBinaryWrite(message.entries[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.MaterialLibrary
 */
export const MaterialLibrary = new MaterialLibrary$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MaterialEntry$Type extends MessageType<MaterialEntry> {
    constructor() {
        super("lightning.v2.MaterialEntry", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "texture_png", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "blend_mode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "is_animated", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "animation_ticks_per_frame", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "animation_frame_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MaterialEntry>): MaterialEntry {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.key = "";
        message.texturePng = new Uint8Array(0);
        message.blendMode = "";
        message.isAnimated = false;
        message.animationTicksPerFrame = 0;
        message.animationFrameCount = 0;
        if (value !== undefined)
            reflectionMergePartial<MaterialEntry>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MaterialEntry): MaterialEntry {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string key */ 1:
                    message.key = reader.string();
                    break;
                case /* bytes texture_png */ 2:
                    message.texturePng = reader.bytes();
                    break;
                case /* string blend_mode */ 3:
                    message.blendMode = reader.string();
                    break;
                case /* bool is_animated */ 4:
                    message.isAnimated = reader.bool();
                    break;
                case /* int32 animation_ticks_per_frame */ 5:
                    message.animationTicksPerFrame = reader.int32();
                    break;
                case /* int32 animation_frame_count */ 6:
                    message.animationFrameCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MaterialEntry, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string key = 1; */
        if (message.key !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.key);
        /* bytes texture_png = 2; */
        if (message.texturePng.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.texturePng);
        /* string blend_mode = 3; */
        if (message.blendMode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.blendMode);
        /* bool is_animated = 4; */
        if (message.isAnimated !== false)
            writer.tag(4, WireType.Varint).bool(message.isAnimated);
        /* int32 animation_ticks_per_frame = 5; */
        if (message.animationTicksPerFrame !== 0)
            writer.tag(5, WireType.Varint).int32(message.animationTicksPerFrame);
        /* int32 animation_frame_count = 6; */
        if (message.animationFrameCount !== 0)
            writer.tag(6, WireType.Varint).int32(message.animationFrameCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.MaterialEntry
 */
export const MaterialEntry = new MaterialEntry$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AnnotationBox$Type extends MessageType<AnnotationBox> {
    constructor() {
        super("lightning.v2.AnnotationBox", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "min", kind: "message", T: () => BlockPos },
            { no: 5, name: "max", kind: "message", T: () => BlockPos },
            { no: 6, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "visible", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "part_refs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PartRef },
            { no: 9, name: "created_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 10, name: "updated_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<AnnotationBox>): AnnotationBox {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.title = "";
        message.description = "";
        message.color = "";
        message.visible = false;
        message.partRefs = [];
        message.createdAt = 0n;
        message.updatedAt = 0n;
        if (value !== undefined)
            reflectionMergePartial<AnnotationBox>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnnotationBox): AnnotationBox {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* lightning.v2.BlockPos min */ 4:
                    message.min = BlockPos.internalBinaryRead(reader, reader.uint32(), options, message.min);
                    break;
                case /* lightning.v2.BlockPos max */ 5:
                    message.max = BlockPos.internalBinaryRead(reader, reader.uint32(), options, message.max);
                    break;
                case /* string color */ 6:
                    message.color = reader.string();
                    break;
                case /* bool visible */ 7:
                    message.visible = reader.bool();
                    break;
                case /* repeated lightning.v2.PartRef part_refs */ 8:
                    message.partRefs.push(PartRef.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int64 created_at */ 9:
                    message.createdAt = reader.int64().toBigInt();
                    break;
                case /* int64 updated_at */ 10:
                    message.updatedAt = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnnotationBox, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* lightning.v2.BlockPos min = 4; */
        if (message.min)
            BlockPos.internalBinaryWrite(message.min, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* lightning.v2.BlockPos max = 5; */
        if (message.max)
            BlockPos.internalBinaryWrite(message.max, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* string color = 6; */
        if (message.color !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.color);
        /* bool visible = 7; */
        if (message.visible !== false)
            writer.tag(7, WireType.Varint).bool(message.visible);
        /* repeated lightning.v2.PartRef part_refs = 8; */
        for (let i = 0; i < message.partRefs.length; i++)
            PartRef.internalBinaryWrite(message.partRefs[i], writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* int64 created_at = 9; */
        if (message.createdAt !== 0n)
            writer.tag(9, WireType.Varint).int64(message.createdAt);
        /* int64 updated_at = 10; */
        if (message.updatedAt !== 0n)
            writer.tag(10, WireType.Varint).int64(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.AnnotationBox
 */
export const AnnotationBox = new AnnotationBox$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PartRef$Type extends MessageType<PartRef> {
    constructor() {
        super("lightning.v2.PartRef", [
            { no: 1, name: "block_pos", kind: "message", T: () => BlockPos },
            { no: 2, name: "part_local_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PartRef>): PartRef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.partLocalId = "";
        if (value !== undefined)
            reflectionMergePartial<PartRef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PartRef): PartRef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* lightning.v2.BlockPos block_pos */ 1:
                    message.blockPos = BlockPos.internalBinaryRead(reader, reader.uint32(), options, message.blockPos);
                    break;
                case /* string part_local_id */ 2:
                    message.partLocalId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PartRef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* lightning.v2.BlockPos block_pos = 1; */
        if (message.blockPos)
            BlockPos.internalBinaryWrite(message.blockPos, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string part_local_id = 2; */
        if (message.partLocalId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.partLocalId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.PartRef
 */
export const PartRef = new PartRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Label$Type extends MessageType<Label> {
    constructor() {
        super("lightning.v2.Label", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "x", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "y", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "z", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "font_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "visible", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Label>): Label {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.text = "";
        message.x = 0;
        message.y = 0;
        message.z = 0;
        message.color = "";
        message.fontSize = 0;
        message.visible = false;
        if (value !== undefined)
            reflectionMergePartial<Label>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Label): Label {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string text */ 2:
                    message.text = reader.string();
                    break;
                case /* float x */ 3:
                    message.x = reader.float();
                    break;
                case /* float y */ 4:
                    message.y = reader.float();
                    break;
                case /* float z */ 5:
                    message.z = reader.float();
                    break;
                case /* string color */ 6:
                    message.color = reader.string();
                    break;
                case /* int32 font_size */ 7:
                    message.fontSize = reader.int32();
                    break;
                case /* bool visible */ 8:
                    message.visible = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Label, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string text = 2; */
        if (message.text !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.text);
        /* float x = 3; */
        if (message.x !== 0)
            writer.tag(3, WireType.Bit32).float(message.x);
        /* float y = 4; */
        if (message.y !== 0)
            writer.tag(4, WireType.Bit32).float(message.y);
        /* float z = 5; */
        if (message.z !== 0)
            writer.tag(5, WireType.Bit32).float(message.z);
        /* string color = 6; */
        if (message.color !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.color);
        /* int32 font_size = 7; */
        if (message.fontSize !== 0)
            writer.tag(7, WireType.Varint).int32(message.fontSize);
        /* bool visible = 8; */
        if (message.visible !== false)
            writer.tag(8, WireType.Varint).bool(message.visible);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.Label
 */
export const Label = new Label$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StatsTemplate$Type extends MessageType<StatsTemplate> {
    constructor() {
        super("lightning.v2.StatsTemplate", [
            { no: 1, name: "mode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "groups", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => StatsGroup },
            { no: 3, name: "show_others", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<StatsTemplate>): StatsTemplate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.mode = "";
        message.groups = [];
        message.showOthers = false;
        if (value !== undefined)
            reflectionMergePartial<StatsTemplate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StatsTemplate): StatsTemplate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string mode */ 1:
                    message.mode = reader.string();
                    break;
                case /* repeated lightning.v2.StatsGroup groups */ 2:
                    message.groups.push(StatsGroup.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool show_others */ 3:
                    message.showOthers = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StatsTemplate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string mode = 1; */
        if (message.mode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.mode);
        /* repeated lightning.v2.StatsGroup groups = 2; */
        for (let i = 0; i < message.groups.length; i++)
            StatsGroup.internalBinaryWrite(message.groups[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool show_others = 3; */
        if (message.showOthers !== false)
            writer.tag(3, WireType.Varint).bool(message.showOthers);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.StatsTemplate
 */
export const StatsTemplate = new StatsTemplate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StatsGroup$Type extends MessageType<StatsGroup> {
    constructor() {
        super("lightning.v2.StatsGroup", [
            { no: 1, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "entries", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => StatsEntry }
        ]);
    }
    create(value?: PartialMessage<StatsGroup>): StatsGroup {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.label = "";
        message.entries = [];
        if (value !== undefined)
            reflectionMergePartial<StatsGroup>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StatsGroup): StatsGroup {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string label */ 1:
                    message.label = reader.string();
                    break;
                case /* repeated lightning.v2.StatsEntry entries */ 2:
                    message.entries.push(StatsEntry.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StatsGroup, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string label = 1; */
        if (message.label !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.label);
        /* repeated lightning.v2.StatsEntry entries = 2; */
        for (let i = 0; i < message.entries.length; i++)
            StatsEntry.internalBinaryWrite(message.entries[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.StatsGroup
 */
export const StatsGroup = new StatsGroup$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StatsEntry$Type extends MessageType<StatsEntry> {
    constructor() {
        super("lightning.v2.StatsEntry", [
            { no: 1, name: "block_state_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "label_override", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "icon_source", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StatsEntry>): StatsEntry {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.blockStateId = "";
        message.labelOverride = "";
        message.iconSource = "";
        if (value !== undefined)
            reflectionMergePartial<StatsEntry>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StatsEntry): StatsEntry {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string block_state_id */ 1:
                    message.blockStateId = reader.string();
                    break;
                case /* string label_override */ 2:
                    message.labelOverride = reader.string();
                    break;
                case /* string icon_source */ 3:
                    message.iconSource = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StatsEntry, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string block_state_id = 1; */
        if (message.blockStateId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.blockStateId);
        /* string label_override = 2; */
        if (message.labelOverride !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.labelOverride);
        /* string icon_source = 3; */
        if (message.iconSource !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.iconSource);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lightning.v2.StatsEntry
 */
export const StatsEntry = new StatsEntry$Type();
