import type { RNAStruct } from '../types'

export const annotationRNA: RNAStruct = {
  name: 'annotation',
  description: '注解对象',
  properties: [
    // ── Common ──
    {
      name: 'title',
      type: 'string',
      label: '标题',
      description: '注解标题',
      default: '',
      get(owner: any) { return owner.title ?? '' },
      set(owner: any, val: unknown) { owner.title = val as string },
    },
    {
      name: 'description',
      type: 'string',
      label: '描述',
      description: '注解描述文本',
      default: '',
      get(owner: any) { return owner.description ?? '' },
      set(owner: any, val: unknown) { owner.description = val as string },
      uiWidget: 'text',
    },
    {
      name: 'color',
      type: 'color',
      label: '颜色',
      description: '注解显示颜色',
      default: '#ffffff',
      get(owner: any) { return owner.color ?? '#ffffff' },
      set(owner: any, val: unknown) { owner.color = val as string },
    },
    {
      name: 'visible',
      type: 'boolean',
      label: '可见',
      description: '是否在视口中可见',
      default: true,
      get(owner: any) { return owner.visible ?? true },
      set(owner: any, val: unknown) { owner.visible = val as boolean },
    },
    {
      name: 'locked',
      type: 'boolean',
      label: '锁定',
      description: '锁定后不可在视口中编辑',
      default: false,
      get(owner: any) { return owner.locked ?? false },
      set(owner: any, val: unknown) { owner.locked = val as boolean },
    },

    // ── Box ──
    {
      name: 'min',
      type: 'vector3',
      label: '最小坐标',
      description: '包围盒最小角',
      default: { x: 0, y: 0, z: 0 },
      get(owner: any) { return owner.min ?? { x: 0, y: 0, z: 0 } },
      set(owner: any, val: unknown) { owner.min = { ...val as any } },
    },
    {
      name: 'max',
      type: 'vector3',
      label: '最大坐标',
      description: '包围盒最大角',
      default: { x: 0, y: 0, z: 0 },
      get(owner: any) { return owner.max ?? { x: 0, y: 0, z: 0 } },
      set(owner: any, val: unknown) { owner.max = { ...val as any } },
    },
    {
      name: 'renderStyle',
      type: 'enum',
      label: '渲染样式',
      description: '包围盒渲染方式',
      default: 'wireframe',
      enumItems: ['wireframe', 'boxFrame', 'translucent', 'hidden'],
      get(owner: any) { return owner.renderStyle ?? 'wireframe' },
      set(owner: any, val: unknown) { owner.renderStyle = val as string },
    },
    {
      name: 'renderOpacity',
      type: 'number',
      label: '不透明度',
      description: '包围盒渲染不透明度 (0-1)',
      default: 0.5,
      min: 0, max: 1,
      get(owner: any) { return owner.renderOpacity ?? 0.5 },
      set(owner: any, val: unknown) { owner.renderOpacity = val as number },
    },
    {
      name: 'overlay',
      type: 'boolean',
      label: '覆盖层',
      description: '浮于顶层，忽略深度遮挡',
      default: false,
      get(owner: any) { return owner.overlay ?? false },
      set(owner: any, val: unknown) { owner.overlay = val as boolean },
    },
    {
      name: 'fillOpacity',
      type: 'number',
      label: '填充不透明度',
      description: '半透明填充不透明度 (0-1)',
      default: 0.3,
      min: 0, max: 1,
      get(owner: any) { return owner.fillOpacity ?? 0.3 },
      set(owner: any, val: unknown) { owner.fillOpacity = val as number },
    },
    {
      name: 'frameThickness',
      type: 'number',
      label: '边框厚度',
      description: 'boxFrame 样式的边框条粗细',
      default: 0.04,
      min: 0.01, max: 0.2,
      get(owner: any) { return owner.frameThickness ?? 0.04 },
      set(owner: any, val: unknown) { owner.frameThickness = val as number },
    },

    // ── Point ──
    {
      name: 'pos',
      type: 'vector3',
      label: '位置',
      description: '标记点世界坐标',
      default: { x: 0, y: 0, z: 0 },
      get(owner: any) { return owner.pos ?? { x: 0, y: 0, z: 0 } },
      set(owner: any, val: unknown) { owner.pos = { ...val as any } },
    },
    {
      name: 'icon',
      type: 'enum',
      label: '图标',
      description: '标记点图标形状',
      default: 'diamond',
      enumItems: ['diamond', 'circle', 'square', 'cross'],
      get(owner: any) { return owner.icon ?? 'diamond' },
      set(owner: any, val: unknown) { owner.icon = val as string },
    },
    {
      name: 'size',
      type: 'number',
      label: '大小',
      description: '标记点尺寸',
      default: 1.0,
      min: 0.1, max: 5,
      get(owner: any) { return owner.size ?? 1.0 },
      set(owner: any, val: unknown) { owner.size = val as number },
    },

    // ── Line ──
    {
      name: 'thickness',
      type: 'number',
      label: '粗细',
      description: '线段粗细',
      default: 1.0,
      min: 0.1, max: 10,
      get(owner: any) { return owner.thickness ?? 1.0 },
      set(owner: any, val: unknown) { owner.thickness = val as number },
    },
    {
      name: 'arrow',
      type: 'enum',
      label: '箭头',
      description: '线段箭头样式',
      default: 'none',
      enumItems: ['none', 'start', 'end', 'both'],
      get(owner: any) { return owner.arrow ?? 'none' },
      set(owner: any, val: unknown) { owner.arrow = val as string },
    },
    {
      name: 'showPoints',
      type: 'boolean',
      label: '显示控制点',
      description: '显示线段端点标记',
      default: true,
      get(owner: any) { return owner.showPoints ?? true },
      set(owner: any, val: unknown) { owner.showPoints = val as boolean },
    },

    // ── Text ──
    {
      name: 'anchorPos',
      type: 'vector3',
      label: '锚点',
      description: '文本标签锚点世界坐标',
      default: { x: 0, y: 0, z: 0 },
      get(owner: any) { return owner.anchorPos ?? { x: 0, y: 0, z: 0 } },
      set(owner: any, val: unknown) { owner.anchorPos = { ...val as any } },
    },
    {
      name: 'text',
      type: 'string',
      label: '内容',
      description: '文本标签内容',
      default: '',
      get(owner: any) { return owner.text ?? '' },
      set(owner: any, val: unknown) { owner.text = val as string },
      uiWidget: 'text',
    },
    {
      name: 'fontSize',
      type: 'number',
      label: '字号',
      description: '文本字号',
      default: 14,
      min: 8, max: 72,
      get(owner: any) { return owner.fontSize ?? 14 },
      set(owner: any, val: unknown) { owner.fontSize = val as number },
    },
    {
      name: 'backgroundAlpha',
      type: 'number',
      label: '背景透明度',
      description: '文本背景 Alpha (0-255)',
      default: 0xCC,
      min: 0, max: 255,
      get(owner: any) { return owner.backgroundAlpha ?? 0xCC },
      set(owner: any, val: unknown) { owner.backgroundAlpha = val as number },
    },
  ],
}
